title: My Github Learning
author: Sayaji Padghan
email: sayaji.padghan@intel.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  My Github learning - work in progress!!!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
